version: "3"
services:
  mongo:
    image: aymen94/mongodb-alpine
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: my-service
    ports:
      - 27017:27017
    volumes:
      - ..:/workspace:cached
  app:
    build: .
    container_name: app
    depends_on:
      - mongo
    volumes:
      - .:/code
    ports:
      - 5000:5000
